[package]
name = "ft5x06"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embedded-hal = "0.2.6"
modular-bitfield-msb = "0.11.2"
defmt = "0.2.0"
